# -*- coding: utf-8 -*-
"""HW2_hash_practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHdWj4VbIPQoL7D2JwZ0bx1SGSzvcWvM
"""

import matplotlib.pyplot as plt


somewhat = "hw2_data.txt"
dictA = {}

#讀檔
with open(somewhat, 'r') as file:
  for line in file:
    food = line.strip()

    if food in dictA:
      dictA[food] += 1  #有就加1
    else:
      dictA[food] = 1  #沒有就加上

#多到少排序
sort = sorted(dictA.items(), key=lambda item: item[1], reverse=True)

food = [item[0] for item in sort]
num = [item[1] for item in sort]

# 畫圖
plt.figure(figsize=(5,3))
plt.bar(food, num, color='blue')

# 標題與標籤
plt.xlabel("food", fontsize=12)
plt.ylabel("times", fontsize=12)
plt.xticks(rotation=45)

#不重複的英文字
differentword = int(len(dictA))
print(f"有 {differentword} 個不重複的英文字")

#每一個英文字出現的次數
print("每一個英文字出現次數：")
for food, num in dictA.items():
    print(f"{food}: {num} 次")

# 顯示圖表
plt.tight_layout()
plt.show()